language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install coverage
  - pip install coveralls
  - pip install nose-cov
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE weconnect;" -U postgres

# Setting environment variables
env:
  - DATABASE_URL=postgresql://postgres:1234567890@localhost/weconnect SECRET_KEY=some_secret_value FLASK_CONFIG=testing

  before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
# command to run tests
script:
  - pytest
  - coverage run --source='.' manage.py test
  - coverage report

# generate code climate report
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -r a1f2bb9c030110934ee69446a387d805d4a8d4fdfe0c1dbf3898e2ce0f36a813

# push report to coveralls.io
after_success:
  - coverage report
  - coveralls
  