language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install coverage
  - pip install coveralls
  - pip install nose-cov
  - pip install -r requirements.txt

# services:
#   - postgresql

# before_script:
#   - psql -c "CREATE DATABASE testdb;" -U postgres

# # Setting environment variables
# env:
#   - DATABASE_URL=postgresql://postgres:1234567890@localhost/testdb SECRET_KEY=Oxa34KLncvfjKEjXkf APP_SETTINGS=config.TestingConfig

# command to run tests
script:
  - pytest
  - coverage run --source='.' manage.py test
  - coverage report

# generate code climate report
after_script:
  - codeclimate-test-reporter

# push report to coveralls.io
after_success:
  - coveralls
  