language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install coverage
  - pip install coveralls
  - pip install nose-cov
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

# Setting environment variables
env:
  - FLASK_CONFIG=testing

# command to run tests
script:
  - pytest
  - coverage run --source='.' manage.py test
  - coverage report

# generate code climate report
after_script:
  - codeclimate-test-reporterb

# push report to coveralls.io
after_success:
  - coverage report
  - coveralls
  