language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing
    - CC_TEST_REPORTER_ID=bb516e756802f0ea8dab9a0e2e8e7e77baf973d868154ca3e6363119b67c2672

# command to run tests
script:
  - pytest
  - coverage run --source='.' manage.py test
  - coverage report

# generate code climate report
after_script:
  - codeclimate-test-reporter

# push report to coveralls.io
after_success:
  - coveralls
